### ISSUE TITLE
Trimmed dependencies

### ISSUE THREAD

**Issue by danielroe** [rdunk/sanity-blocks-vue-component#10]
At the moment this package depends on `@sanity/client` through a number of other dependencies. Would it be possible to refactor so this package could be a bit lighter?

**Comment by rdunk** [comment]
Hi @danielroe. I can't see `@sanity/client` in the dependency graph. Can you give me some more information? I have stepped away from using Sanity over the past few months so I'm not up-to-date with current developments.

**Comment by danielroe** [comment]
@rdunk You're quite right! Consider this retracted; I misread the type import in `@sanity/image-url`.
