### ISSUE TITLE
Add option to specify container element

### ISSUE THREAD

**Issue by jorngeorg** [rdunk/sanity-blocks-vue-component#3]
Current all the blocks are wrapped in a `div`.
It would be nice to be able to specify the containing element either as a simple string or a component.
For example if you know all the blocks will be list-elements, one should be able to wrap them in an`ul`-element. 

The React package does this through the `serializers.container` prop.

**Comment by rdunk** [comment]
Hey @jorngeorg, had a quick look at this. Is this not already possible by setting the `serializers.container` prop?

**Comment by jorngeorg** [comment]
Is it? I'm not sure how this is strung together but, the `ContainerSerializer` function returns a div:

`function ContainerSerializer(props) {
    let properties = null
    const containerClass = props.className
    if (containerClass) {
      properties = {
        class: containerClass
      }
    }
    return h('div', properties, props.children)
  }`

**Comment by jorngeorg** [comment]
You're right. Works perfectly. Should just update the readme then!

**Comment by rdunk** [comment]
Might look into copying a lot of the readme content from the React package as the functionality should mostly be the same (will also add support for `renderContainerOnSingleChild` shortly).

**Comment by rdunk** [comment]
Updated, hopefully the readme is a little bit clearer now.
